# Create docker image from Dockerfile
docker build -t airflow_1 .


# Run docker container with bind local folder to docker folder
# docker run -it -p 8080:8080 --add-host=host.docker.internal:host-gateway  --mount type=bind,source=c:/Users/olega/airflow/dags/,target=/root/airflow/dags 24036ab9aacf
docker run -it -p 8080:8080 --add-host=host.docker.internal:host-gateway  --mount type=bind,source=c:/Users/olega/airflow/dags/,target=/root/airflow/dags airflow_1
